### ISSUE TITLE
Bundling oddity

### ISSUE THREAD

**Issue by RainerAtSpirit** [PulsarBlow/aureliaonfire#4]
It looks like that with the default `bundles.json` every package in `dist/aurelia` gets bundled in `dist/app-build` as well. 

My guess is that the bundler doesn't de-deplux dependencies.

By explicitly adding them to the `excludes` array, the result start looking like expected: `app-build.js` is down to 41.7 KB instead of 1.1 MB. 
In the example below I added a dedicated `app/vendor` bundle and set `minify: false` for `dist/app-build` for easier tracking what's in the bundled version. I also had to change the glob pattern for the includes otherwise the bundler wouldn't bundle files in sub folders.

``` json
{
  "bundles": {
    "dist/app-build": {
      "includes": [
        "*/**/*",
        "*/**/*.html!text",
        "*/**/*.css!text"
      ],
      "excludes" :[
        "aurelia-framework",
        "aurelia-bootstrapper",
        "aurelia-fetch-client",
        "aurelia-router",
        "aurelia-animator-css",
        "aurelia-templating-binding",
        "aurelia-templating-resources",
        "aurelia-templating-router",
        "aurelia-loader-default",
        "aurelia-history-browser",
        "aurelia-logging-console",
        "aurelia-firebase",
        "moment",
        "firebase",
        "nprogress"
      ],
      "options": {
        "inject": true,
        "minify": false
      }
    },
    "dist/vendor": {
      "includes": [
        "aurelia-firebase",
        "moment",
        "firebase",
        "nprogress"
      ],
      "options": {
        "inject": true,
        "minify": true
      }
    },
    "dist/aurelia": {
      "includes": [
        "aurelia-framework",
        "aurelia-bootstrapper",
        "aurelia-fetch-client",
        "aurelia-router",
        "aurelia-animator-css",
        "aurelia-templating-binding",
        "aurelia-templating-resources",
        "aurelia-templating-router",
        "aurelia-loader-default",
        "aurelia-history-browser",
        "aurelia-logging-console"
      ],
      "options": {
        "inject": true,
        "minify": true
      }
    }
  }
}
```

**Comment by PulsarBlow** [comment]
Thanks for submitting your bundle config.
I changed the current bundle config but there is a bug in the current bundler version :
https://github.com/aurelia/bundler/issues/34

The automatic dependency tree de-duplication should be handled by the bundler.
